rcon:
    address: "192.168.1.31"
    password: "123123123"
    port: 25575
discord:
    token: "NzcwODczMzMyNTU1MzE3MjU4.X5j5vA.0H8gMw9-eYbu1S_GH3f08zTl9SE"
    channel: 770624629412593666
minecraft:
    log_dir: "./server/logs/latest.log"